version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile                   # The Dockerfile inside the context folder
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 19V299332n02
      DB_NAME: notification
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 19V299332n02
      MYSQL_DATABASE: notification
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
