apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assessment-management
  template:
    metadata:
      labels:
        app: assessment-management
    spec:
      containers:
        - name: assessment-management
          image: assessment-management:latest
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: assessment-management
spec:
  type: ClusterIP
  selector:
    app: assessment-management
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
