apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-video-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinic-video-management
  template:
    metadata:
      labels:
        app: clinic-video-management
    spec:
      containers:
        - name: clinic-video-management
          image: clinic-video-management:latest
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: clinic-video-management
spec:
  type: ClusterIP
  selector:
    app: clinic-video-management
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
