apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exercise-management
  template:
    metadata:
      labels:
        app: exercise-management
    spec:
      containers:
        - name: exercise-management
          image: exercise-management:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: exercise-management
spec:
  type: ClusterIP
  selector:
    app: exercise-management
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
