apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: user-management:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
  type: ClusterIP
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
